# Generated by Django 4.1.5 on 2023-02-02 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("name", models.CharField(max_length=255)),
                (
                    "bvn",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("email", models.EmailField(max_length=254, null=True, unique=True)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "customer",
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="creditapp.customer",
                    ),
                ),
                ("score", models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TransactionSummary",
            fields=[
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="creditapp.customer",
                    ),
                ),
                ("credit_sum", models.FloatField()),
                ("debit_sum", models.FloatField()),
                ("credit_count", models.IntegerField()),
                ("debit_count", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_date", models.DateTimeField()),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("CREDIT", "Credit"), ("DEBIT", "Debit")],
                        default="Credit",
                        max_length=20,
                    ),
                ),
                ("transaction_amount", models.FloatField()),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer",
                        to="creditapp.customer",
                    ),
                ),
            ],
        ),
    ]
